# Generated by Django 6.0 on 2026-01-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0003_main_movie_video_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_movie',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
